eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10009/eureka/
server:
  port: 10031
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consumner-fegin
    api-b:
      path: /api-b/**
      serviceId: consumner-ribbon

