server:
  port: 10012 # 10011 10012

eureka:
  client:
    service-url:
     defaultZone: http://localhost:10009/eureka/

spring:
  application:
    name: provider
  zipkin:
    base-url: http://localhost:9411
