server:
  port: 10121
spring:
  application:
    name: consumner-ribbon
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10009/eureka/
